language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn ci-check
